
---

## Version of the config file, do not touch
configversion: 3

## Permissions node:
## These can be used with or without the permissions plugin
## set it to 'permissions' to make it use the permissions plugin or bukkitperms
## set it to 'none' to disable the node
## set it to 'all' to make the node available to all users
## set it to 'op' to make the node available to op's
## the warning has an extra option 'server' where the warning is only printed to the server

## This node is to get information about yourself.
## Like your own ip, or connected accounts to own ip address
self node: permissions
## This node is to get information about someone else
other node: permissions
## Node to get the warning messages
warning node: permissions
## Node to use the aipban command
aipban node: permissions

## This is the maximum size of the iplist (for command /iplist)
max iplist size: 6

## Sends a warning about users with an IP that is also used by other players.
## This is send to all players with the warning node and the server.
## You can set it to 'firstjoin', 'always' or 'off'
warn double ip: firstjoin

## Syntax on how the data is printed
## See folling website for more info: http://download.oracle.com/javase/1.4.2/docs/api/java/text/SimpleDateFormat.html
date syntax: dd-MMM-yyyy HH:mm

## What IPNotify must use to store its data
## Supported are "flatfile", "mysql" or "sqllite"
datasource: flatfile

## Mysql information
mysql:
  username: ipnotify
  password: ipnotify
  location: 127.0.0.1
  dbname: ipnotify

   
    
...